/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivRouteImport } from './routes/archiv'
import { Route as HinweiseRouteImport } from './routes/hinweise'
import { Route as NeuRouteImport } from './routes/neu'
import { Route as TenorhilfeRouteImport } from './routes/tenorhilfe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivRoute = ArchivRouteImport.update({
  id: '/archiv',
  path: '/archiv',
  getParentRoute: () => rootRouteImport,
} as any)
const HinweiseRoute = HinweiseRouteImport.update({
  id: '/hinweise',
  path: '/hinweise',
  getParentRoute: () => rootRouteImport,
} as any)
const NeuRoute = NeuRouteImport.update({
  id: '/neu',
  path: '/neu',
  getParentRoute: () => rootRouteImport,
} as any)
const TenorhilfeRoute = TenorhilfeRouteImport.update({
  id: '/tenorhilfe',
  path: '/tenorhilfe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archiv': typeof ArchivRoute
  '/hinweise': typeof HinweiseRoute
  '/neu': typeof NeuRoute
  '/tenorhilfe': typeof TenorhilfeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archiv': typeof ArchivRoute
  '/hinweise': typeof HinweiseRoute
  '/neu': typeof NeuRoute
  '/tenorhilfe': typeof TenorhilfeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archiv': typeof ArchivRoute
  '/hinweise': typeof HinweiseRoute
  '/neu': typeof NeuRoute
  '/tenorhilfe': typeof TenorhilfeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/archiv' | '/hinweise' | '/neu' | '/tenorhilfe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archiv' | '/hinweise' | '/neu' | '/tenorhilfe'
  id: '__root__' | '/' | '/archiv' | '/hinweise' | '/neu' | '/tenorhilfe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivRoute: typeof ArchivRoute
  HinweiseRoute: typeof HinweiseRoute
  NeuRoute: typeof NeuRoute
  TenorhilfeRoute: typeof TenorhilfeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archiv': {
      id: '/archiv'
      path: '/archiv'
      fullPath: '/archiv'
      preLoaderRoute: typeof ArchivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hinweise': {
      id: '/hinweise'
      path: '/hinweise'
      fullPath: '/hinweise'
      preLoaderRoute: typeof HinweiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neu': {
      id: '/neu'
      path: '/neu'
      fullPath: '/neu'
      preLoaderRoute: typeof NeuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenorhilfe': {
      id: '/tenorhilfe'
      path: '/tenorhilfe'
      fullPath: '/tenorhilfe'
      preLoaderRoute: typeof TenorhilfeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivRoute: ArchivRoute,
  HinweiseRoute: HinweiseRoute,
  NeuRoute: NeuRoute,
  TenorhilfeRoute: TenorhilfeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
